#ifndef _CONFIG_H_
#define _CONFIG_H_

#define CONFIG_FONT_COMIC_NEUE_25x28
#define CONFIG_FONT_LIBERATION_SANS_15x16
#define CONFIG_FONT_LIBERATION_SERIF_19x19
#define CONFIG_FONT_UBUNTU_MONO_6x10

#define CONFIG_SSD1306_DYNAMIC_ALLOC

#endif
